### ISSUE TITLE
Cant require from nodejs, window is not defined

### ISSUE THREAD

**Issue by jpambrun** [dcmjs-org/dcmjs#28]
Doing the following :
``` shell
> npm init -y
> npm install npmjs
> node
>> const dcmjs = require('dcmjs')
ReferenceError: window is not defined
    at Object.<anonymous> (/home/jpambrun/tmp/dcmjs_test/node_modules/dcmjs/build/dcmjs.js:1:262)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)

```

**Comment by jpambrun** [comment]
This bug : https://github.com/webpack/webpack/issues/6784

**Comment by pieper** [comment]
Thanks for the report - I guess if this is a webpack issue we can just wait for it to be resolved there.

**Comment by pieper** [comment]
That workaround seems reasonable to me - I don't know what the impact would be.  dcmjs itself doesn't care at all about the browser environment.

@galelis do you have any ideas on this?
