### ISSUE TITLE
TypeError: log.create is not a function

### ISSUE THREAD

**Issue by JAVA-NOVACHOK** [dcmjs-org/dcmjs#411]
With new version 0.34.4 I started to get this error. Switched to 0.34.0 and it is working fine. 
Could you look at it?

TypeError: log.create is not a function
    at /builds/idgital/test-automation/node_modules/dcmjs/src/log.js:8:27
    at /builds/idgital/test-automation/node_modules/dcmjs/build/dcmjs.js:2:65
    at Object.<anonymous> (/builds/idgital/test-automation/node_modules/dcmjs/build/dcmjs.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/builds/idgital/test-automation/cache/Cypress/13.15.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:851:20)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/builds/idgital/test-automation/cypress.config.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (/builds/idgital/test-automation/cache/Cypress/13.15.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:857:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/builds/idgital/test-automation/cache/Cypress/13.15.0/Cypress/resources/app/node_modules/ts-node/dist/index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at loadFile (/builds/idgital/test-automation/cache/Cypress/13.15.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/builds/idgital/test-automation/cache/Cypress/13.15.0/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:513:28)

**Comment by igoroctaviano** [comment]
Fixed by #412. Thanks!
